//----- This Script generated by ChatGPT -----


import { test, expect } from '@playwright/test';

test('Validate flight search from Portland to Rome', async ({ page }) => {
  // Navigate to BlazeDemo
  await page.goto('https://blazedemo.com');

  // Select departure and destination cities
  await page.selectOption('select[name="fromPort"]', {
    label: 'Portland',
  });

  await page.selectOption('select[name="toPort"]', {
    label: 'Rome',
  });

  // Click Find Flights
  await page.click('input[type="submit"]');

  // Verify navigation to reserve page
  await expect(page).toHaveURL(/reserve\.php/);

  // Validate there are exactly 5 flight rows
  const flightRows = page.locator('table tbody tr');
  await expect(flightRows).toHaveCount(5);

  // Optional: Print the flight count
  console.log(`Flights displayed: ${await flightRows.count()}`);
});
  


